esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi_ssid_1
    password: !secret wifi_password_1
  - ssid: !secret wifi_ssid_2
    password: !secret wifi_password_2
  domain: !secret wifi_domain
  ap:
    ssid: ${devicename}_fallback_hotspot
    password: !secret password

captive_portal:

logger:

api:
  password: !secret password

ota:
  password: !secret password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${devicename}_button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: ${devicename}_relay
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
