#!/bin/sh
echo "Current working directory: '$(pwd)'"
if [ -c /dev/ttyUSB0 ]; then
  docker run --rm --net=host --device=/dev/ttyUSB0 -v "$(pwd)":/config -e ESPHOME_DASHBOARD_USE_PING=true -it esphome/esphome "$@"
else
  docker run --rm --net=host -v "$(pwd)":/config -e ESPHOME_DASHBOARD_USE_PING=true -it esphome/esphome "$@"
fi
