substitutions:
  devicename: ir_bridge_1
  address: "0x08E7"
  power: "0x807F"
  mute: "0x00FF"
  volume_down: "0x30CF"
  volume_up: "0x906F"
  line_1: "0x50AF"
  line_2: "0xA857"
  optical: "0xB04F"
  coaxial: "0x6897"
  bluetooth: "0x708F"
  play_pause: "0x28D7"
  seek_back: "0x609F"
  seek_forward: "0x10EF"
  delay: 200ms

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
  domain: !secret wifi_domain
  ap:
    ssid: ${devicename}_fallback_hotspot
    password: !secret password

captive_portal:

logger:

api:
  password: !secret password

ota:
  password: !secret password

remote_receiver:
  pin:
    number: D1
    mode: INPUT_PULLUP
    inverted: True
  dump: all

remote_transmitter:
  pin: D2
  # Infrared remotes use a 50% carrier signal
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: Edifier Power
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${power}
  - platform: template
    name: Edifier Mute
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${mute}
  - platform: template
    name: Edifier Volume Down
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${volume_down}
  - platform: template
    name: Edifier Volume Up
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${volume_up}
  - platform: template
    name: Edifier Line 1
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${line_1}
  - platform: template
    name: Edifier Line 2
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${line_2}
  - platform: template
    name: Edifier Optical
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${optical}
  - platform: template
    name: Edifier Coaxial
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${coaxial}
  - platform: template
    name: Edifier Bluetooth
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${bluetooth}
  - platform: template
    name: Edifier Play/Pause
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${play_pause}
  - platform: template
    name: Edifier Seek Back
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${seek_back}
  - platform: template
    name: Edifier Seek Forward
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: ${address}
          command: ${seek_forward}

binary_sensor:
  - platform: remote_receiver
    name: "Edifier Power"
    nec:
      address: ${address}
      command: ${power}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Mute"
    nec:
      address: ${address}
      command: ${mute}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Volume Down"
    nec:
      address: ${address}
      command: ${volume_down}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Volume Up"
    nec:
      address: ${address}
      command: ${volume_up}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Line 1"
    nec:
      address: ${address}
      command: ${line_1}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Line 2"
    nec:
      address: ${address}
      command: ${line_2}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Optical"
    nec:
      address: ${address}
      command: ${optical}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Coaxial"
    nec:
      address: ${address}
      command: ${coaxial}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Bluetooth"
    nec:
      address: ${address}
      command: ${bluetooth}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Play/Pause"
    nec:
      address: ${address}
      command: ${play_pause}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Seek Back"
    nec:
      address: ${address}
      command: ${seek_back}
    filters:
      - delayed_off: ${delay}
  - platform: remote_receiver
    name: "Edifier Seek Forward"
    nec:
      address: ${address}
      command: ${seek_forward}
    filters:
      - delayed_off: ${delay}
