# WIP

substitutions:
  devicename: rf_bridge_1
  delay: 200ms

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
  domain: !secret wifi_domain
  ap:
    ssid: ${devicename}_fallback_hotspot
    password: !secret password

captive_portal:

logger:

api:
  password: !secret password

ota:
  password: !secret password

remote_receiver:
  pin: D1
  dump:
    - rc_switch
  tolerance: 80%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb

binary_sensor:
  - platform: remote_receiver
    name: "unitec_a_on"
    rc_switch_raw:
      code: "011101010100111101011100"
      protocol: 2
    filters:
      - delayed_off: ${delay}
